kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gcp-ws-deployment
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gcp-ws-deployment
    spec:
      containers:
        - name: gcp-ws-container
          image: YOUR_IMAGE_URL
          ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: gcp-ws-service
spec:
  type: LoadBalancer
  selector:
    app: gcp-ws-deployment
  ports:
    - port: 80
      targetPort: 80
